// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEvent = `-- name: CreateEvent :one
insert into events (
    slug, title, organizer_tz,
    window_start, window_end, day_start, day_end, slot_minutes
) values (
    $1, $2, $3, $4, $5, $6, $7, $8
)
returning id, slug, title, organizer_tz, window_start, window_end, day_start, day_end, slot_minutes, status, decided_slot_start, created_at, expires_at, group_id, decided_at
`

type CreateEventParams struct {
	Slug        string
	Title       string
	OrganizerTz string
	WindowStart pgtype.Date
	WindowEnd   pgtype.Date
	DayStart    pgtype.Time
	DayEnd      pgtype.Time
	SlotMinutes int32
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.Slug,
		arg.Title,
		arg.OrganizerTz,
		arg.WindowStart,
		arg.WindowEnd,
		arg.DayStart,
		arg.DayEnd,
		arg.SlotMinutes,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.OrganizerTz,
		&i.WindowStart,
		&i.WindowEnd,
		&i.DayStart,
		&i.DayEnd,
		&i.SlotMinutes,
		&i.Status,
		&i.DecidedSlotStart,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.GroupID,
		&i.DecidedAt,
	)
	return i, err
}

const createEventInGroup = `-- name: CreateEventInGroup :one
insert into events (
    slug, title, organizer_tz,
    window_start, window_end, day_start, day_end, slot_minutes, group_id
) values (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
returning id, slug, title, organizer_tz, window_start, window_end, day_start, day_end, slot_minutes, status, decided_slot_start, created_at, expires_at, group_id, decided_at
`

type CreateEventInGroupParams struct {
	Slug        string
	Title       string
	OrganizerTz string
	WindowStart pgtype.Date
	WindowEnd   pgtype.Date
	DayStart    pgtype.Time
	DayEnd      pgtype.Time
	SlotMinutes int32
	GroupID     pgtype.UUID
}

func (q *Queries) CreateEventInGroup(ctx context.Context, arg CreateEventInGroupParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEventInGroup,
		arg.Slug,
		arg.Title,
		arg.OrganizerTz,
		arg.WindowStart,
		arg.WindowEnd,
		arg.DayStart,
		arg.DayEnd,
		arg.SlotMinutes,
		arg.GroupID,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.OrganizerTz,
		&i.WindowStart,
		&i.WindowEnd,
		&i.DayStart,
		&i.DayEnd,
		&i.SlotMinutes,
		&i.Status,
		&i.DecidedSlotStart,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.GroupID,
		&i.DecidedAt,
	)
	return i, err
}

const decideEvent = `-- name: DecideEvent :one
update events
set status = 'decided', decided_slot_start = $2, decided_at = now()
where id = $1
returning id, slug, title, organizer_tz, window_start, window_end, day_start, day_end, slot_minutes, status, decided_slot_start, created_at, expires_at, group_id, decided_at
`

type DecideEventParams struct {
	ID               pgtype.UUID
	DecidedSlotStart pgtype.Timestamptz
}

func (q *Queries) DecideEvent(ctx context.Context, arg DecideEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, decideEvent, arg.ID, arg.DecidedSlotStart)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.OrganizerTz,
		&i.WindowStart,
		&i.WindowEnd,
		&i.DayStart,
		&i.DayEnd,
		&i.SlotMinutes,
		&i.Status,
		&i.DecidedSlotStart,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.GroupID,
		&i.DecidedAt,
	)
	return i, err
}

const deleteExpiredEvents = `-- name: DeleteExpiredEvents :execrows
delete from events
where id in (
    select id from events
    where expires_at < now()
    order by expires_at
    limit $1
)
`

// Deletes rather than tombstones. The privacy note in the README promises the
// data goes away when the link expires, and a row marked 'expired' still holds
// every name and every busy interval. Participants, responses and busy blocks
// follow through `on delete cascade`; groups survive, because both references
// into events are `on delete set null`.
//
// The limit bounds one pass so a first sweep over a long-neglected table
// cannot hold a transaction open across millions of rows. The caller loops
// until a pass comes back short.
func (q *Queries) DeleteExpiredEvents(ctx context.Context, limit int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredEvents, limit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getEventBySlug = `-- name: GetEventBySlug :one
select id, slug, title, organizer_tz, window_start, window_end, day_start, day_end, slot_minutes, status, decided_slot_start, created_at, expires_at, group_id, decided_at from events where slug = $1
`

func (q *Queries) GetEventBySlug(ctx context.Context, slug string) (Event, error) {
	row := q.db.QueryRow(ctx, getEventBySlug, slug)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.OrganizerTz,
		&i.WindowStart,
		&i.WindowEnd,
		&i.DayStart,
		&i.DayEnd,
		&i.SlotMinutes,
		&i.Status,
		&i.DecidedSlotStart,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.GroupID,
		&i.DecidedAt,
	)
	return i, err
}

const linkEventToGroup = `-- name: LinkEventToGroup :one
update events set group_id = $2
where id = $1
returning id, slug, title, organizer_tz, window_start, window_end, day_start, day_end, slot_minutes, status, decided_slot_start, created_at, expires_at, group_id, decided_at
`

type LinkEventToGroupParams struct {
	ID      pgtype.UUID
	GroupID pgtype.UUID
}

func (q *Queries) LinkEventToGroup(ctx context.Context, arg LinkEventToGroupParams) (Event, error) {
	row := q.db.QueryRow(ctx, linkEventToGroup, arg.ID, arg.GroupID)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.OrganizerTz,
		&i.WindowStart,
		&i.WindowEnd,
		&i.DayStart,
		&i.DayEnd,
		&i.SlotMinutes,
		&i.Status,
		&i.DecidedSlotStart,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.GroupID,
		&i.DecidedAt,
	)
	return i, err
}

const reopenEvent = `-- name: ReopenEvent :one
update events
set status = 'open', decided_slot_start = null, decided_at = null
where id = $1
returning id, slug, title, organizer_tz, window_start, window_end, day_start, day_end, slot_minutes, status, decided_slot_start, created_at, expires_at, group_id, decided_at
`

func (q *Queries) ReopenEvent(ctx context.Context, id pgtype.UUID) (Event, error) {
	row := q.db.QueryRow(ctx, reopenEvent, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.OrganizerTz,
		&i.WindowStart,
		&i.WindowEnd,
		&i.DayStart,
		&i.DayEnd,
		&i.SlotMinutes,
		&i.Status,
		&i.DecidedSlotStart,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.GroupID,
		&i.DecidedAt,
	)
	return i, err
}
