// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: groups.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimGroupMember = `-- name: ClaimGroupMember :one
update group_members set token_hash = $2
where id = $1
returning id, group_id, token_hash, display_name, tz, default_role, calendar_source, calendar_url, joined_at
`

type ClaimGroupMemberParams struct {
	ID        pgtype.UUID
	TokenHash []byte
}

func (q *Queries) ClaimGroupMember(ctx context.Context, arg ClaimGroupMemberParams) (GroupMember, error) {
	row := q.db.QueryRow(ctx, claimGroupMember, arg.ID, arg.TokenHash)
	var i GroupMember
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.TokenHash,
		&i.DisplayName,
		&i.Tz,
		&i.DefaultRole,
		&i.CalendarSource,
		&i.CalendarUrl,
		&i.JoinedAt,
	)
	return i, err
}

const createGroup = `-- name: CreateGroup :one
insert into groups (slug, name, created_from)
values ($1, $2, $3)
returning id, slug, name, created_from, created_at
`

type CreateGroupParams struct {
	Slug        string
	Name        string
	CreatedFrom pgtype.UUID
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, createGroup, arg.Slug, arg.Name, arg.CreatedFrom)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.CreatedFrom,
		&i.CreatedAt,
	)
	return i, err
}

const createGroupMember = `-- name: CreateGroupMember :one
insert into group_members (group_id, token_hash, display_name, tz, default_role)
values ($1, $2, $3, $4, $5)
returning id, group_id, token_hash, display_name, tz, default_role, calendar_source, calendar_url, joined_at
`

type CreateGroupMemberParams struct {
	GroupID     pgtype.UUID
	TokenHash   []byte
	DisplayName string
	Tz          string
	DefaultRole string
}

func (q *Queries) CreateGroupMember(ctx context.Context, arg CreateGroupMemberParams) (GroupMember, error) {
	row := q.db.QueryRow(ctx, createGroupMember,
		arg.GroupID,
		arg.TokenHash,
		arg.DisplayName,
		arg.Tz,
		arg.DefaultRole,
	)
	var i GroupMember
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.TokenHash,
		&i.DisplayName,
		&i.Tz,
		&i.DefaultRole,
		&i.CalendarSource,
		&i.CalendarUrl,
		&i.JoinedAt,
	)
	return i, err
}

const createParticipantFromGroupMember = `-- name: CreateParticipantFromGroupMember :one
insert into participants (
    event_id, token_hash, display_name, tz, role, group_member_id
) values (
    $1, $2, $3, $4, $5, $6
)
returning id, event_id, token_hash, display_name, tz, role, email, calendar_source, is_organizer, responded_at, created_at, calendar_url, group_member_id
`

type CreateParticipantFromGroupMemberParams struct {
	EventID       pgtype.UUID
	TokenHash     []byte
	DisplayName   string
	Tz            string
	Role          string
	GroupMemberID pgtype.UUID
}

func (q *Queries) CreateParticipantFromGroupMember(ctx context.Context, arg CreateParticipantFromGroupMemberParams) (Participant, error) {
	row := q.db.QueryRow(ctx, createParticipantFromGroupMember,
		arg.EventID,
		arg.TokenHash,
		arg.DisplayName,
		arg.Tz,
		arg.Role,
		arg.GroupMemberID,
	)
	var i Participant
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.TokenHash,
		&i.DisplayName,
		&i.Tz,
		&i.Role,
		&i.Email,
		&i.CalendarSource,
		&i.IsOrganizer,
		&i.RespondedAt,
		&i.CreatedAt,
		&i.CalendarUrl,
		&i.GroupMemberID,
	)
	return i, err
}

const deleteGroupMemberBusyBlocks = `-- name: DeleteGroupMemberBusyBlocks :exec
delete from group_member_busy_blocks where group_member_id = $1
`

func (q *Queries) DeleteGroupMemberBusyBlocks(ctx context.Context, groupMemberID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteGroupMemberBusyBlocks, groupMemberID)
	return err
}

const getGroupByID = `-- name: GetGroupByID :one
select id, slug, name, created_from, created_at from groups where id = $1
`

func (q *Queries) GetGroupByID(ctx context.Context, id pgtype.UUID) (Group, error) {
	row := q.db.QueryRow(ctx, getGroupByID, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.CreatedFrom,
		&i.CreatedAt,
	)
	return i, err
}

const getGroupBySlug = `-- name: GetGroupBySlug :one
select id, slug, name, created_from, created_at from groups where slug = $1
`

func (q *Queries) GetGroupBySlug(ctx context.Context, slug string) (Group, error) {
	row := q.db.QueryRow(ctx, getGroupBySlug, slug)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.CreatedFrom,
		&i.CreatedAt,
	)
	return i, err
}

const getGroupMemberByID = `-- name: GetGroupMemberByID :one
select id, group_id, token_hash, display_name, tz, default_role, calendar_source, calendar_url, joined_at from group_members where id = $1 and group_id = $2
`

type GetGroupMemberByIDParams struct {
	ID      pgtype.UUID
	GroupID pgtype.UUID
}

func (q *Queries) GetGroupMemberByID(ctx context.Context, arg GetGroupMemberByIDParams) (GroupMember, error) {
	row := q.db.QueryRow(ctx, getGroupMemberByID, arg.ID, arg.GroupID)
	var i GroupMember
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.TokenHash,
		&i.DisplayName,
		&i.Tz,
		&i.DefaultRole,
		&i.CalendarSource,
		&i.CalendarUrl,
		&i.JoinedAt,
	)
	return i, err
}

const getGroupMemberByIDUnscoped = `-- name: GetGroupMemberByIDUnscoped :one
select id, group_id, token_hash, display_name, tz, default_role, calendar_source, calendar_url, joined_at from group_members where id = $1
`

// Used only where the caller has already established which group this id
// belongs to through some other verified path (a checked token, an id read
// back from a row already scoped to the right group). ClaimEventSeat is the
// one caller: by the time it runs, the event's own group_id has already
// picked out which group this member id must belong to.
func (q *Queries) GetGroupMemberByIDUnscoped(ctx context.Context, id pgtype.UUID) (GroupMember, error) {
	row := q.db.QueryRow(ctx, getGroupMemberByIDUnscoped, id)
	var i GroupMember
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.TokenHash,
		&i.DisplayName,
		&i.Tz,
		&i.DefaultRole,
		&i.CalendarSource,
		&i.CalendarUrl,
		&i.JoinedAt,
	)
	return i, err
}

const getGroupMemberByToken = `-- name: GetGroupMemberByToken :one
select id, group_id, token_hash, display_name, tz, default_role, calendar_source, calendar_url, joined_at from group_members where group_id = $1 and token_hash = $2
`

type GetGroupMemberByTokenParams struct {
	GroupID   pgtype.UUID
	TokenHash []byte
}

func (q *Queries) GetGroupMemberByToken(ctx context.Context, arg GetGroupMemberByTokenParams) (GroupMember, error) {
	row := q.db.QueryRow(ctx, getGroupMemberByToken, arg.GroupID, arg.TokenHash)
	var i GroupMember
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.TokenHash,
		&i.DisplayName,
		&i.Tz,
		&i.DefaultRole,
		&i.CalendarSource,
		&i.CalendarUrl,
		&i.JoinedAt,
	)
	return i, err
}

const getParticipantByGroupMember = `-- name: GetParticipantByGroupMember :one
select id, event_id, token_hash, display_name, tz, role, email, calendar_source, is_organizer, responded_at, created_at, calendar_url, group_member_id from participants where event_id = $1 and group_member_id = $2
`

type GetParticipantByGroupMemberParams struct {
	EventID       pgtype.UUID
	GroupMemberID pgtype.UUID
}

func (q *Queries) GetParticipantByGroupMember(ctx context.Context, arg GetParticipantByGroupMemberParams) (Participant, error) {
	row := q.db.QueryRow(ctx, getParticipantByGroupMember, arg.EventID, arg.GroupMemberID)
	var i Participant
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.TokenHash,
		&i.DisplayName,
		&i.Tz,
		&i.Role,
		&i.Email,
		&i.CalendarSource,
		&i.IsOrganizer,
		&i.RespondedAt,
		&i.CreatedAt,
		&i.CalendarUrl,
		&i.GroupMemberID,
	)
	return i, err
}

const insertGroupMemberBusyBlocks = `-- name: InsertGroupMemberBusyBlocks :exec
insert into group_member_busy_blocks (group_member_id, start_ts, end_ts, source)
select $1, unnest($2::timestamptz[]), unnest($3::timestamptz[]), $4
`

type InsertGroupMemberBusyBlocksParams struct {
	GroupMemberID pgtype.UUID
	Column2       []pgtype.Timestamptz
	Column3       []pgtype.Timestamptz
	Source        string
}

func (q *Queries) InsertGroupMemberBusyBlocks(ctx context.Context, arg InsertGroupMemberBusyBlocksParams) error {
	_, err := q.db.Exec(ctx, insertGroupMemberBusyBlocks,
		arg.GroupMemberID,
		arg.Column2,
		arg.Column3,
		arg.Source,
	)
	return err
}

const listGroupDecisions = `-- name: ListGroupDecisions :many
select decided_slot_start, decided_at
from events
where group_id = $1 and status = 'decided' and decided_slot_start is not null and decided_at is not null
order by decided_at desc
`

type ListGroupDecisionsRow struct {
	DecidedSlotStart pgtype.Timestamptz
	DecidedAt        pgtype.Timestamptz
}

// Past decisions the group actually settled on, oldest information excluded by
// nothing here -- decay is applied in Go, where the half-life constant lives
// next to the rest of the scoring model rather than duplicated in SQL.
func (q *Queries) ListGroupDecisions(ctx context.Context, groupID pgtype.UUID) ([]ListGroupDecisionsRow, error) {
	rows, err := q.db.Query(ctx, listGroupDecisions, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGroupDecisionsRow{}
	for rows.Next() {
		var i ListGroupDecisionsRow
		if err := rows.Scan(&i.DecidedSlotStart, &i.DecidedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupEvents = `-- name: ListGroupEvents :many
select id, slug, title, organizer_tz, window_start, window_end, day_start, day_end, slot_minutes, status, decided_slot_start, created_at, expires_at, group_id, decided_at from events where group_id = $1 order by created_at desc
`

func (q *Queries) ListGroupEvents(ctx context.Context, groupID pgtype.UUID) ([]Event, error) {
	rows, err := q.db.Query(ctx, listGroupEvents, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.OrganizerTz,
			&i.WindowStart,
			&i.WindowEnd,
			&i.DayStart,
			&i.DayEnd,
			&i.SlotMinutes,
			&i.Status,
			&i.DecidedSlotStart,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.GroupID,
			&i.DecidedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupMemberBusyBlocks = `-- name: ListGroupMemberBusyBlocks :many
select id, group_member_id, start_ts, end_ts, source, fetched_at from group_member_busy_blocks where group_member_id = $1 order by start_ts
`

func (q *Queries) ListGroupMemberBusyBlocks(ctx context.Context, groupMemberID pgtype.UUID) ([]GroupMemberBusyBlock, error) {
	rows, err := q.db.Query(ctx, listGroupMemberBusyBlocks, groupMemberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GroupMemberBusyBlock{}
	for rows.Next() {
		var i GroupMemberBusyBlock
		if err := rows.Scan(
			&i.ID,
			&i.GroupMemberID,
			&i.StartTs,
			&i.EndTs,
			&i.Source,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupMembers = `-- name: ListGroupMembers :many
select id, group_id, token_hash, display_name, tz, default_role, calendar_source, calendar_url, joined_at from group_members where group_id = $1 order by joined_at, id
`

func (q *Queries) ListGroupMembers(ctx context.Context, groupID pgtype.UUID) ([]GroupMember, error) {
	rows, err := q.db.Query(ctx, listGroupMembers, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GroupMember{}
	for rows.Next() {
		var i GroupMember
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.TokenHash,
			&i.DisplayName,
			&i.Tz,
			&i.DefaultRole,
			&i.CalendarSource,
			&i.CalendarUrl,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rotateParticipantToken = `-- name: RotateParticipantToken :one
update participants set token_hash = $2
where id = $1
returning id, event_id, token_hash, display_name, tz, role, email, calendar_source, is_organizer, responded_at, created_at, calendar_url, group_member_id
`

type RotateParticipantTokenParams struct {
	ID        pgtype.UUID
	TokenHash []byte
}

func (q *Queries) RotateParticipantToken(ctx context.Context, arg RotateParticipantTokenParams) (Participant, error) {
	row := q.db.QueryRow(ctx, rotateParticipantToken, arg.ID, arg.TokenHash)
	var i Participant
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.TokenHash,
		&i.DisplayName,
		&i.Tz,
		&i.Role,
		&i.Email,
		&i.CalendarSource,
		&i.IsOrganizer,
		&i.RespondedAt,
		&i.CreatedAt,
		&i.CalendarUrl,
		&i.GroupMemberID,
	)
	return i, err
}

const setGroupMemberCalendar = `-- name: SetGroupMemberCalendar :exec
update group_members
set calendar_source = $2, calendar_url = $3
where id = $1
`

type SetGroupMemberCalendarParams struct {
	ID             pgtype.UUID
	CalendarSource string
	CalendarUrl    pgtype.Text
}

func (q *Queries) SetGroupMemberCalendar(ctx context.Context, arg SetGroupMemberCalendarParams) error {
	_, err := q.db.Exec(ctx, setGroupMemberCalendar, arg.ID, arg.CalendarSource, arg.CalendarUrl)
	return err
}
