// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type BusyBlock struct {
	ID            pgtype.UUID
	ParticipantID pgtype.UUID
	StartTs       pgtype.Timestamptz
	EndTs         pgtype.Timestamptz
	Source        string
	FetchedAt     pgtype.Timestamptz
}

type Event struct {
	ID               pgtype.UUID
	Slug             string
	Title            string
	OrganizerTz      string
	WindowStart      pgtype.Date
	WindowEnd        pgtype.Date
	DayStart         pgtype.Time
	DayEnd           pgtype.Time
	SlotMinutes      int32
	Status           string
	DecidedSlotStart pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	ExpiresAt        pgtype.Timestamptz
}

type Participant struct {
	ID             pgtype.UUID
	EventID        pgtype.UUID
	TokenHash      []byte
	DisplayName    string
	Tz             string
	Role           string
	Email          pgtype.Text
	CalendarSource string
	IsOrganizer    bool
	RespondedAt    pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	CalendarUrl    pgtype.Text
}

type Response struct {
	ParticipantID pgtype.UUID
	SlotStart     pgtype.Timestamptz
	Tier          int16
	Source        string
}
