// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Event struct {
	ID               pgtype.UUID
	Slug             string
	Title            string
	OrganizerTz      string
	WindowStart      pgtype.Date
	WindowEnd        pgtype.Date
	DayStart         pgtype.Time
	DayEnd           pgtype.Time
	SlotMinutes      int32
	Status           string
	DecidedSlotStart pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	ExpiresAt        pgtype.Timestamptz
}
