// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: participants.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createParticipant = `-- name: CreateParticipant :one
insert into participants (
    event_id, token_hash, display_name, tz, role, is_organizer
) values (
    $1, $2, $3, $4, $5, $6
)
returning id, event_id, token_hash, display_name, tz, role, email, calendar_source, is_organizer, responded_at, created_at
`

type CreateParticipantParams struct {
	EventID     pgtype.UUID
	TokenHash   []byte
	DisplayName string
	Tz          string
	Role        string
	IsOrganizer bool
}

func (q *Queries) CreateParticipant(ctx context.Context, arg CreateParticipantParams) (Participant, error) {
	row := q.db.QueryRow(ctx, createParticipant,
		arg.EventID,
		arg.TokenHash,
		arg.DisplayName,
		arg.Tz,
		arg.Role,
		arg.IsOrganizer,
	)
	var i Participant
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.TokenHash,
		&i.DisplayName,
		&i.Tz,
		&i.Role,
		&i.Email,
		&i.CalendarSource,
		&i.IsOrganizer,
		&i.RespondedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getParticipantByToken = `-- name: GetParticipantByToken :one
select id, event_id, token_hash, display_name, tz, role, email, calendar_source, is_organizer, responded_at, created_at from participants where event_id = $1 and token_hash = $2
`

type GetParticipantByTokenParams struct {
	EventID   pgtype.UUID
	TokenHash []byte
}

func (q *Queries) GetParticipantByToken(ctx context.Context, arg GetParticipantByTokenParams) (Participant, error) {
	row := q.db.QueryRow(ctx, getParticipantByToken, arg.EventID, arg.TokenHash)
	var i Participant
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.TokenHash,
		&i.DisplayName,
		&i.Tz,
		&i.Role,
		&i.Email,
		&i.CalendarSource,
		&i.IsOrganizer,
		&i.RespondedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listParticipants = `-- name: ListParticipants :many
select id, event_id, token_hash, display_name, tz, role, email, calendar_source, is_organizer, responded_at, created_at from participants where event_id = $1 order by created_at, id
`

func (q *Queries) ListParticipants(ctx context.Context, eventID pgtype.UUID) ([]Participant, error) {
	rows, err := q.db.Query(ctx, listParticipants, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Participant{}
	for rows.Next() {
		var i Participant
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.TokenHash,
			&i.DisplayName,
			&i.Tz,
			&i.Role,
			&i.Email,
			&i.CalendarSource,
			&i.IsOrganizer,
			&i.RespondedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markParticipantResponded = `-- name: MarkParticipantResponded :exec
update participants set responded_at = now() where id = $1
`

func (q *Queries) MarkParticipantResponded(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markParticipantResponded, id)
	return err
}
