// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: participants.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createParticipant = `-- name: CreateParticipant :one
insert into participants (
    event_id, token_hash, display_name, tz, role, is_organizer
) values (
    $1, $2, $3, $4, $5, $6
)
returning id, event_id, token_hash, display_name, tz, role, email, calendar_source, is_organizer, responded_at, created_at, calendar_url, group_member_id
`

type CreateParticipantParams struct {
	EventID     pgtype.UUID
	TokenHash   []byte
	DisplayName string
	Tz          string
	Role        string
	IsOrganizer bool
}

func (q *Queries) CreateParticipant(ctx context.Context, arg CreateParticipantParams) (Participant, error) {
	row := q.db.QueryRow(ctx, createParticipant,
		arg.EventID,
		arg.TokenHash,
		arg.DisplayName,
		arg.Tz,
		arg.Role,
		arg.IsOrganizer,
	)
	var i Participant
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.TokenHash,
		&i.DisplayName,
		&i.Tz,
		&i.Role,
		&i.Email,
		&i.CalendarSource,
		&i.IsOrganizer,
		&i.RespondedAt,
		&i.CreatedAt,
		&i.CalendarUrl,
		&i.GroupMemberID,
	)
	return i, err
}

const deleteBusyBlocks = `-- name: DeleteBusyBlocks :exec
delete from busy_blocks where participant_id = $1
`

func (q *Queries) DeleteBusyBlocks(ctx context.Context, participantID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteBusyBlocks, participantID)
	return err
}

const getParticipantByToken = `-- name: GetParticipantByToken :one
select id, event_id, token_hash, display_name, tz, role, email, calendar_source, is_organizer, responded_at, created_at, calendar_url, group_member_id from participants where event_id = $1 and token_hash = $2
`

type GetParticipantByTokenParams struct {
	EventID   pgtype.UUID
	TokenHash []byte
}

func (q *Queries) GetParticipantByToken(ctx context.Context, arg GetParticipantByTokenParams) (Participant, error) {
	row := q.db.QueryRow(ctx, getParticipantByToken, arg.EventID, arg.TokenHash)
	var i Participant
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.TokenHash,
		&i.DisplayName,
		&i.Tz,
		&i.Role,
		&i.Email,
		&i.CalendarSource,
		&i.IsOrganizer,
		&i.RespondedAt,
		&i.CreatedAt,
		&i.CalendarUrl,
		&i.GroupMemberID,
	)
	return i, err
}

const insertBusyBlocks = `-- name: InsertBusyBlocks :exec
insert into busy_blocks (participant_id, start_ts, end_ts, source)
select $1, unnest($2::timestamptz[]), unnest($3::timestamptz[]), $4
`

type InsertBusyBlocksParams struct {
	ParticipantID pgtype.UUID
	Column2       []pgtype.Timestamptz
	Column3       []pgtype.Timestamptz
	Source        string
}

func (q *Queries) InsertBusyBlocks(ctx context.Context, arg InsertBusyBlocksParams) error {
	_, err := q.db.Exec(ctx, insertBusyBlocks,
		arg.ParticipantID,
		arg.Column2,
		arg.Column3,
		arg.Source,
	)
	return err
}

const linkParticipantToGroupMember = `-- name: LinkParticipantToGroupMember :one
update participants set group_member_id = $2
where id = $1
returning id, event_id, token_hash, display_name, tz, role, email, calendar_source, is_organizer, responded_at, created_at, calendar_url, group_member_id
`

type LinkParticipantToGroupMemberParams struct {
	ID            pgtype.UUID
	GroupMemberID pgtype.UUID
}

func (q *Queries) LinkParticipantToGroupMember(ctx context.Context, arg LinkParticipantToGroupMemberParams) (Participant, error) {
	row := q.db.QueryRow(ctx, linkParticipantToGroupMember, arg.ID, arg.GroupMemberID)
	var i Participant
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.TokenHash,
		&i.DisplayName,
		&i.Tz,
		&i.Role,
		&i.Email,
		&i.CalendarSource,
		&i.IsOrganizer,
		&i.RespondedAt,
		&i.CreatedAt,
		&i.CalendarUrl,
		&i.GroupMemberID,
	)
	return i, err
}

const listBusyBlocks = `-- name: ListBusyBlocks :many
select id, participant_id, start_ts, end_ts, source, fetched_at from busy_blocks where participant_id = $1 order by start_ts
`

func (q *Queries) ListBusyBlocks(ctx context.Context, participantID pgtype.UUID) ([]BusyBlock, error) {
	rows, err := q.db.Query(ctx, listBusyBlocks, participantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BusyBlock{}
	for rows.Next() {
		var i BusyBlock
		if err := rows.Scan(
			&i.ID,
			&i.ParticipantID,
			&i.StartTs,
			&i.EndTs,
			&i.Source,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listParticipants = `-- name: ListParticipants :many
select id, event_id, token_hash, display_name, tz, role, email, calendar_source, is_organizer, responded_at, created_at, calendar_url, group_member_id from participants where event_id = $1 order by created_at, id
`

func (q *Queries) ListParticipants(ctx context.Context, eventID pgtype.UUID) ([]Participant, error) {
	rows, err := q.db.Query(ctx, listParticipants, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Participant{}
	for rows.Next() {
		var i Participant
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.TokenHash,
			&i.DisplayName,
			&i.Tz,
			&i.Role,
			&i.Email,
			&i.CalendarSource,
			&i.IsOrganizer,
			&i.RespondedAt,
			&i.CreatedAt,
			&i.CalendarUrl,
			&i.GroupMemberID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markParticipantResponded = `-- name: MarkParticipantResponded :exec
update participants set responded_at = now() where id = $1
`

func (q *Queries) MarkParticipantResponded(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markParticipantResponded, id)
	return err
}

const setCalendarSource = `-- name: SetCalendarSource :exec
update participants
set calendar_source = $2, calendar_url = $3
where id = $1
`

type SetCalendarSourceParams struct {
	ID             pgtype.UUID
	CalendarSource string
	CalendarUrl    pgtype.Text
}

func (q *Queries) SetCalendarSource(ctx context.Context, arg SetCalendarSourceParams) error {
	_, err := q.db.Exec(ctx, setCalendarSource, arg.ID, arg.CalendarSource, arg.CalendarUrl)
	return err
}
