// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"context"
)

type Querier interface {
	CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error)
	GetEventBySlug(ctx context.Context, slug string) (Event, error)
}

var _ Querier = (*Queries)(nil)
