// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: responses.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteResponsesForParticipant = `-- name: DeleteResponsesForParticipant :exec
delete from responses where participant_id = $1
`

func (q *Queries) DeleteResponsesForParticipant(ctx context.Context, participantID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteResponsesForParticipant, participantID)
	return err
}

const insertResponses = `-- name: InsertResponses :exec
insert into responses (participant_id, slot_start, tier, source)
select
    $1,
    unnest($2::timestamptz[]),
    unnest($3::smallint[]),
    unnest($4::text[])
`

type InsertResponsesParams struct {
	ParticipantID pgtype.UUID
	Column2       []pgtype.Timestamptz
	Column3       []int16
	Column4       []string
}

func (q *Queries) InsertResponses(ctx context.Context, arg InsertResponsesParams) error {
	_, err := q.db.Exec(ctx, insertResponses,
		arg.ParticipantID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	return err
}

const listResponsesForEvent = `-- name: ListResponsesForEvent :many
select r.participant_id, r.slot_start, r.tier, r.source
from responses r
join participants p on p.id = r.participant_id
where p.event_id = $1
order by r.participant_id, r.slot_start
`

func (q *Queries) ListResponsesForEvent(ctx context.Context, eventID pgtype.UUID) ([]Response, error) {
	rows, err := q.db.Query(ctx, listResponsesForEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Response{}
	for rows.Next() {
		var i Response
		if err := rows.Scan(
			&i.ParticipantID,
			&i.SlotStart,
			&i.Tier,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResponsesForParticipant = `-- name: ListResponsesForParticipant :many
select participant_id, slot_start, tier, source from responses where participant_id = $1 order by slot_start
`

func (q *Queries) ListResponsesForParticipant(ctx context.Context, participantID pgtype.UUID) ([]Response, error) {
	rows, err := q.db.Query(ctx, listResponsesForParticipant, participantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Response{}
	for rows.Next() {
		var i Response
		if err := rows.Scan(
			&i.ParticipantID,
			&i.SlotStart,
			&i.Tier,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
